### ISSUE TITLE
Git workflow for AMI stack: provide diagram

### ISSUE THREAD

**Issue by ghost** [ContentMine/meta#14]
@petermr has requested that a better diagram of the proposed Git workflow for the AMI stack be found or created, than that linked at https://github.com/ContentMine/meta/issues/11#issue-232836000 .

**Comment by sampablokuper** [comment]
Fixed. Image placed at https://github.com/ContentMine/meta/wiki/Git-workflow and copied to #11.

**Comment by ghost** [comment]
@petermr , am closing this as have now placed diagram at https://github.com/ContentMine/meta/wiki/Git-workflow and copied it to #11.
